### ISSUE TITLE
depends on RTCGAToolbox 2.7.5 -- cannot find!

### ISSUE THREAD

**Issue by vjcitn** [waldronlab/TCGAutils#5] opened 2017-09-05 18:42 UTC
Error in loadNamespace(j <- imp[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘RTCGAToolbox’ 2.7.0 is being loaded, but >= 2.7.5 is required
ERROR: lazy loading failed for package ‘TCGAutils’

maybe it is my lack of git strength?  all i see in bioc is 2.7.0, devel branch

**Comment by LiNk-NY** [comment] 2017-09-05 18:47
Hi Vince, @vjcitn
Thanks creating this issue. The repo is located under:
```
BiocInstaller::biocLite("LiNK-NY/RTCGAToolbox")
```
I will add this note to the README in `TCGAutils`

**Comment by lwaldron** [comment] 2017-09-05 19:42
Since your RTCGAToolbox is likely permanently disconnected from Mehmet's, and it is no longer actively maintained, would it be practical to put the relevant code in TCGAutils as non-exported functions and get rid of the dependency?

**Comment by LiNk-NY** [comment] 2017-09-05 20:02
Hi Levi, @lwaldron
The relevant code is integral to `RTCGAToolbox`. The improvements are mostly in naming consistency so to facilitate seamless extraction of data types.
Please see: 
https://github.com/mksamur/RTCGAToolbox/compare/master...LiNk-NY:master
for a difference between forks. 
It seems to me like these can be merged after a few improvements, namely removing `@` from messages on my branch. 
Regards,
Marcel

**Comment by LiNk-NY** [comment] 2017-09-06 18:47
**Update**: It's possible that https://github.com/mksamur/RTCGAToolbox is out of sync with the Bioconductor repository. I have contacted Mehmet about this. More to follow. For now, the issue is closed.

**Closed as completed by LiNk-NY** 2017-09-06 18:47 UTC
